[python-MySQL 教學](https://www.edureka.co/blog/python-database-connection/)

In [ ]:
https://thepiguy.altervista.org/dht11mysql-python/

In [1]:
# import pymysql
# 需使用pip install mysql-connector-python
import mysql.connector

connect = mysql.connector.connect(host="127.0.0.1", user="root", password="123", auth_plugin='mysql_native_password')

print(connect)

if (connect):
    print("Connection Successful")
else:
    print("Connection Unsuccessful")
    
cursor = connect.cursor()

cursor.execute("SELECT VERSION()")
data = cursor.fetchone()

print ("Database version : %s " % data)

cursor.execute("SHOW DATABASES")

databases = cursor.fetchall()

for database in databases:
    print(database)
    
connect.close()
print('closs database!')

<mysql.connector.connection_cext.CMySQLConnection object at 0x7fb02e11ec88>
Connection Successful
Database version : 8.0.21
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)
('test1',)
closs database!

In [2]:
# 練習
import mysql.connector
 
connect = mysql.connector.connect(host="127.0.0.1", user="root", password="123", database='test2', auth_plugin='mysql_native_password')
cursor=connect.cursor()

# 創建 Database 名為 test2
# cursor.execute("create database test2")

# 創建 table 名為 employee
# cursor.execute("create table tempdata2(name varchar(250),sal int(20))")

# 創建 table 名為 tempdata (變數 Date,Amb_Temperature, Obj_Temperature)
# cursor.execute("create table tempdata(Date varchar(200),Amb_Temperature varchar(200),Obj_Temperature varchar(200))")

# 刪除 table 名為 tempdata
# cursor.execute("DROP TABLE tempdata")

# 查看 table
# cursor.execute("show tables")
# for tb in cursor:
#     print(tb)

In [1]:
import socket
import time
import mysql.connector
import datetime

HEADERSIZE = 10

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
# s.bind((socket.gethostname(), 6688))
s.bind(('140.134.29.25', 6688))
s.listen(5)

BUFFER_SIZE = 1024  # Normally 1024, but we want fast response

connect = mysql.connector.connect(host="127.0.0.1", user="root", password="123", database="test2", auth_plugin='mysql_native_password')
if (connect):
    print("Connection Successful")
else:
    print("Connection Unsuccessful")

cursor = connect.cursor()

        
def get_date():
    unix = int(time.time())
    date = str(datetime.datetime.fromtimestamp(unix).strftime('%Y-%m-%d %H:%M:%S'))
    return date
    
    
def process_data_from_client(x):
    amb, obj = x.split(" ")
    return amb, obj


while True:
    # now our endpoint knows about the OTHER endpoint.
    clientsocket, address = s.accept()
    print(f"Connection from {address} has been established.")
    
    msg = "Welcome to the server!"
    msg = f"{len(msg):<{HEADERSIZE}}"+msg
    
    clientsocket.send(bytes(msg,"utf-8"))
    
    while True:
        recdata = clientsocket.recv(BUFFER_SIZE).decode('utf-8')
        amb, obj = process_data_from_client(recdata)
        date = get_date()
        print(date, amb, obj)
        
        # Write data to the database
        cursor.execute("INSERT INTO tempdata (Date, Amb_Temperature, Obj_Temperature) VALUES (%s, %s, %s)",(date, amb, obj)) # values has placeholders
        connect.commit() # SQL statement used for saving the changes
#         print(recdata)
        if not recdata:
            break
        else:
            pass
# close socket
s.close()
# close mysql
cursor.close
connect.close()

In [ ]:
while True:
    try:
        data += sock.recv(1024)
        data_end = data.find('\n')
        
        if data_end!=-1:
            rec=data[:data_end+1:]
            print(data)

In [16]:
# 練習
import mysql.connector
import pandas as pd
 
connect = mysql.connector.connect(host="127.0.0.1", user="root", password="123", database='test2', auth_plugin='mysql_native_password')
cursor=connect.cursor()

# df = pd.read_sql("SELECT Amb_Temperature FROM tempdata2 ", connect)
df = pd.read_sql("SELECT * FROM tempdata2 ", connect)
# X = df.Data.values[-10:]
print(df)
# print(X)

# 創建 Database 名為 test2
# cursor.execute("create database test2")

# 創建 table 名為 employee
# cursor.execute("create table tempdata2(name varchar(250),sal int(20))")

# 創建 table 名為 tempdata (變數 Data,Amb_Temperature, Obj_Temperature)
# cursor.execute("create table tempdata2(Data varchar(200),Amb_Temperature varchar(200),Obj_Temperature varchar(200))")

# 查看 table
# cursor.execute("show tables")
# for tb in cursor:
#     print(tb)

# Data Amb_Temperature Obj_Temperature

                   Data Amb_Temperature Obj_Temperature
0   2020-08-18 21:05:31          25.430          26.830
1   2020-08-18 21:05:32          25.430          27.150
2   2020-08-18 21:05:33          25.410          27.030
3   2020-08-18 21:05:34          25.430          27.110
4   2020-08-18 21:05:35          25.430          27.030
5   2020-08-18 21:05:36          25.410          27.050
6   2020-08-18 21:05:37          25.450          27.050
7   2020-08-18 21:05:38          25.430          26.990
8   2020-08-18 21:05:39          25.430          26.850
9   2020-08-18 21:05:40          25.430          26.850
10  2020-08-18 21:05:41          25.430          26.970
11  2020-08-18 21:05:42          25.450          26.990
12  2020-08-18 21:05:43          25.450          26.990
13  2020-08-18 21:05:44          25.450          26.830
14  2020-08-18 21:05:45          25.430          27.110
15  2020-08-18 21:05:46          25.470          26.930
16  2020-08-18 21:05:47          25.450          26.870
17  2020-08-18 21:05:48          25.470          32.770
18  2020-08-18 21:05:49          25.430          32.250
19  2020-08-18 21:05:50          25.470          32.210
20  2020-08-18 21:05:51          25.530          32.350
21  2020-08-18 21:05:52          25.510          32.670
22  2020-08-18 21:05:53          25.510          32.670
23  2020-08-18 21:05:54          25.510          32.830
24  2020-08-18 21:05:55          25.530          32.950
25  2020-08-18 21:05:56          25.550          28.650
26  2020-08-18 21:05:57          25.610          27.910
27  2020-08-18 21:05:58          25.650          27.470
28  2020-08-18 21:05:59          25.650          27.530
29  2020-08-18 21:06:00          25.690          27.490
30  2020-08-18 21:06:01          25.690          27.630
31  2020-08-18 21:06:02          25.690          27.470
32  2020-08-18 21:06:03          25.690          27.730
33  2020-08-18 21:06:04          25.710          27.610
34  2020-08-18 21:06:05          25.690          27.470
35  2020-08-18 21:06:06          25.690          27.290
36  2020-08-18 21:06:07          25.710          27.430
37  2020-08-18 21:06:08          25.650          27.550